mujin/mujincontrollerclientpy

python/mujincontrollerclient/realtimeitlplanningclient.py
Mostly added visualization API supports.
=> DMS 2016 changes

python/mujincontrollerclient/planningclient.py
fixed cannot zoom in or out when tracking objects
=> add ispan to viewercommand to fix bug that cannot zoom out viewer

python/mujincontrollerclient/realtimerobotclient.py
added servo on/off interface to realtime robot controller client
=> added servo on/off interface to realtime robot controller client

python/mujincontrollerclient/realtimerobotclient.py
Support for add gripper from template and save gripper to database
=> Support for add gripper from template and save gripper to database

python/mujincontrollerclient/controllerclientbase.py, python/mujincontrollerclient/realtimeitlplanning3client.py
initial commit of friction test - functions added for support of friction test between realtimerobottask3.py and systemmanager.py
=> Feature4119

python/mujincontrollerclient/__init__.py, python/mujincontrollerclient/controllerclientbase.py, python/mujincontrollerclient/controllerclientraw.py
Support for uploading STL with Japanese name
- commonui (jpsupport)
- mujincontrollerclientpy (jpsupport)
- planningcommon (jpsupport)
- webstack (jpsupport)
=> Support for uploading STL with Japanese name

python/mujincontrollerclient/controllerclientbase.py
When scene has more than 20 instobjects, sensor mapping might not get set because it is outside of the page size.
=> Fix set sensor mapping.

python/mujincontrollerclient/controllerclientbase.py
improves error message for #4409
=> check for bad input

python/mujincontrollerclient/realtimerobotclient.py
To share device settings across robots, separate device settings from robot settings.
=> Move device settings out of robot settings

python/mujincontrollerclient/controllerclientbase.py, python/mujincontrollerclient/controllerclientraw.py
Explicit login against mujin controller is not necessary since March 2016.
=> Remove excessive login requests.

python/mujincontrollerclient/controllerclientbase.py
=> Add GetConfig API.

python/mujincontrollerclient/uriutils.py, python/mujintestcontrollerclient/test_uriutils.py
a pretty commonly used conversion.
=> Add GetURIFromPartType and test case

python/mujincontrollerclient/handeyecalibrationcontrollerclient.py
Update controller client code to reflect changes in planningcommon calibration pose generation code.
Requires:
dev/planningcommon!656  on gitlab
dev/calibration!59  on gitlab
controllerclientcpp/#49
=> Calibrationplanning

python/mujincontrollerclient/zmqclient.py
to be used from robotbridgeclient
=> zmqclient: add preemption callback, expose parameters to constructor

python/mujincontrollerclient/controllerclientbase.py, python/mujincontrollerclient/planningclient.py
Client side implementation for setting component log levels for planning and vision.
=> Component logger debug level setting

bin/mujin_controllerclientpy_applyconfig.py
With this patch a wild card can be used a part of preserved parameter name like `calibrationParameters.*.savedposes`.
=> Add wildcard support to applyconfig.py

python/mujincontrollerclient/binpickingcontrollerclient.py, python/mujincontrollerclient/realtimerobotclient.py, python/mujincontrollerclient/version.py
move ResetCachedRobotConfigurationState to realtimerobotclient to avoid checking of function existence in controllerclient.
=> move ResetCachedRobotConfigurationState 

python/mujincontrollerclient/realtimerobotclient.py
Adds documentation to the functions in `RealtimeRobotClient` in Google Docstring format. To reduce the size of later PRs for client generation.
Only changes docstrings, no changes to the code.
Passes on autotester: https://autotester.test.mujin.co.jp/?scheduleid=2&pipelineid=253274
=> Fix docstrings in realtimerobotclient.py

python/mujincontrollerclient/realtimerobotclient.py
This PR removes functions and parameters that have no effect (the server has no corresponding functions so the call returns without doing anything).
Autotester: https://autotester.test.mujin.co.jp/?scheduleid=2&pipelineid=257387
=> Remove unused functions and parameters from realtimerobotclient

python/mujincontrollerclient/binpickingcontrollerclient.py, python/mujincontrollerclient/planningclient.py, python/mujincontrollerclient/realtimerobotclient.py
Follow-up to https://github.com/mujin/mujincontrollerclientpy/pull/107.
No code changes, just doc.
=> Improve docstrings

python/mujincontrollerclient/realtimerobotclient.py
Rearranging some lines so they are easier to generate. Should not affect behavior.
=> Rearrange bodieslist logic in ReplaceBodies
